window.ObsNotes = (() => {
  function clean(html){const source=document.createElement('div');source.innerHTML=html||'';const out=document.createElement('div');function walk(node,parent){if(node.nodeType===3){parent.append(document.createTextNode(node.textContent));return;}if(node.nodeType!==1)return;if(['SCRIPT','STYLE','IFRAME','OBJECT'].includes(node.tagName))return;const tag=['H1','H2','H3','H4','H5','H6'].includes(node.tagName)?'DIV':node.tagName==='SPAN'&&(/bold|[7-9]00/.test(node.style.fontWeight))?'STRONG':node.tagName;const allowed=['B','STRONG','BR','DIV','P','UL','OL','LI'].includes(tag),dest=allowed?document.createElement(tag.toLowerCase()):parent;if(allowed)parent.append(dest);for(const child of node.childNodes)walk(child,dest);}for(const child of source.childNodes)walk(child,out);return out.innerHTML;}
  function mount(config){
    const dialog=config.dialog,area=document.getElementById('obsTextarea'),container=document.getElementById('obsContent');
    const extras=document.createElement('section');extras.className='obs-exam';extras.innerHTML='<p id="obsSavedDate" class="obs-note-date"></p><label for="obsExamFile">Exame do aluno</label><input id="obsExamFile" type="file" accept="image/*"><div class="obs-exam-photo" hidden><button type="button" id="obsExamView" aria-label="Ampliar foto do exame"><img id="obsExamImage" alt="Exame do aluno"></button><button type="button" id="obsExamDelete">Apagar foto</button></div><label for="obsExamResult">Resultado do exame</label><div id="obsExamResult" class="obs-rich-text" contenteditable="true" role="textbox" aria-multiline="true" aria-label="Resultado do exame"></div><p id="obsNotesStatus" role="status"></p>';
    container.append(extras);
    const toolbar=document.createElement('div');toolbar.className='obs-notes-toolbar';toolbar.setAttribute('aria-label','Editar observações');toolbar.innerHTML='<button type="button" id="obsBoldBtn" title="Negrito"><b>B</b> (Negrito)</button><button type="button" id="obsUndoBtn" aria-label="Desfazer observação">↶</button><button type="button" id="obsRedoBtn" aria-label="Refazer observação">↷</button><button type="button" id="obsCopyPrescriptionBtn">📋 Copiar prescrição para OBS</button>';
    container.prepend(toolbar);
    const result=document.getElementById('obsExamResult'),status=document.getElementById('obsNotesStatus'),date=document.getElementById('obsSavedDate'),photo=document.getElementById('obsExamImage'),file=document.getElementById('obsExamFile');
    area.before(date);
    const histories=new WeakMap();let editing=area,range=null,pending=0;
    function text(editor){return editor.innerText.replace(/\r/g,'');}
    function capture(){const g=config.guide();if(!g)return;g.texto=text(area);g.textoHtml=clean(area.innerHTML);g.exameResultado=text(result);g.exameResultadoHtml=clean(result.innerHTML);}
    Object.defineProperty(area,'value',{get(){return text(area);},set(value){const g=config.guide();area.innerHTML=g&&g.texto===value&&g.textoHtml?clean(g.textoHtml):'';if(!area.innerHTML)area.textContent=value||'';}});
    function snapshot(){return [area.innerHTML,result.innerHTML];}
    function history(){const g=config.guide();if(!g)return null;let h=histories.get(g);if(!h){h={items:[snapshot()],at:0};histories.set(g,h);}return h;}
    function record(){const h=history();if(!h)return;const s=snapshot();if(JSON.stringify(h.items[h.at])!==JSON.stringify(s)){h.items.splice(h.at+1);h.items.push(s);if(h.items.length>80)h.items.shift();h.at=h.items.length-1;}capture();buttons();}
    function buttons(){const h=history();document.getElementById('obsUndoBtn').disabled=!h||h.at===0;document.getElementById('obsRedoBtn').disabled=!h||h.at===h.items.length-1;}
    function refresh(){const g=config.guide()||{};area.value=g.texto||'';result.innerHTML=clean(g.exameResultadoHtml||'');if(!result.innerHTML)result.textContent=g.exameResultado||'';date.textContent=g.obsSalvaEm?'OBS salva em '+new Date(g.obsSalvaEm).toLocaleString('pt-BR'):'';photo.parentElement.parentElement.hidden=!g.exameFoto;if(g.exameFoto)photo.src=g.exameFoto;else photo.removeAttribute('src');file.value='';range=null;editing=area;buttons();}
    [area,result].forEach(editor=>{editor.addEventListener('focus',()=>{editing=editor;history();});editor.addEventListener('input',record);editor.addEventListener('paste',event=>{event.preventDefault();const html=event.clipboardData.getData('text/html'),plain=event.clipboardData.getData('text/plain');if(html)document.execCommand('insertHTML',false,clean(html));else if(/\*\*[^*]+\*\*/.test(plain)){const escaped=document.createElement('div');escaped.textContent=plain;document.execCommand('insertHTML',false,escaped.innerHTML.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>'));}else document.execCommand('insertText',false,plain);record();});editor.addEventListener('keydown',event=>{if(!(event.ctrlKey||event.metaKey))return;const key=event.key.toLowerCase();if(key==='b'){event.preventDefault();bold();}if(key==='z'||key==='y'){event.preventDefault();move(key==='y'||event.shiftKey?1:-1);}});});
    document.addEventListener('selectionchange',()=>{if(!dialog.open)return;const sel=getSelection();if(!sel.rangeCount)return;const r=sel.getRangeAt(0);if(editing.contains(r.commonAncestorContainer))range=r.cloneRange();});
    function restore(){editing.focus({preventScroll:true});if(range&&editing.contains(range.commonAncestorContainer)){const sel=getSelection();sel.removeAllRanges();sel.addRange(range);}}
    function bold(){restore();document.execCommand('bold',false,null);record();}
    function move(step){const h=history();if(!h||!h.items[h.at+step])return;h.at+=step;[area.innerHTML,result.innerHTML]=h.items[h.at];range=null;capture();buttons();editing.focus({preventScroll:true});}
    [['obsBoldBtn',bold],['obsUndoBtn',()=>move(-1)],['obsRedoBtn',()=>move(1)]].forEach(([id,fn])=>{const b=document.getElementById(id);b.addEventListener('pointerdown',e=>e.preventDefault());b.onclick=fn;});
    document.getElementById('obsCopyPrescriptionBtn').onclick=()=>{history();const prescription=config.prescription();if(!prescription){status.textContent='Não há prescrição neste treino.';return;}const separator=document.createTextNode(text(area).trim()?'\n\n':'');area.append(separator,document.createTextNode(prescription));editing=area;record();status.textContent='Prescrição adicionada à OBS. Toque em Salvar somente OBS para guardar.';};
    file.onchange=async()=>{const selected=file.files[0],g=config.guide();if(!selected||!g)return;pending++;status.textContent='Preparando foto…';try{if(!selected.type.startsWith('image/'))throw Error('Escolha uma imagem do exame.');const bitmap=await createImageBitmap(selected,{imageOrientation:'from-image'}),scale=Math.min(1,1400/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();g.exameFoto=canvas.toDataURL('image/jpeg',0.72);if(config.guide()===g){photo.src=g.exameFoto;photo.parentElement.parentElement.hidden=false;status.textContent='Foto pronta. Salve a OBS para guardar.';}}catch(error){status.textContent='Não foi possível carregar a foto: '+error.message;}finally{pending--;file.value='';}};
    document.getElementById('obsExamDelete').onclick=()=>{const g=config.guide();if(!g)return;delete g.exameFoto;photo.removeAttribute('src');photo.parentElement.parentElement.hidden=true;status.textContent='Foto removida. Salve a OBS para guardar.';};
    const viewer=document.createElement('dialog');viewer.className='app-dialog obs-exam-viewer';viewer.innerHTML='<button type="button">Fechar foto</button><img alt="Exame ampliado">';document.body.append(viewer);viewer.querySelector('button').onclick=()=>viewer.close();document.getElementById('obsExamView').onclick=()=>{viewer.querySelector('img').src=photo.src;viewer.showModal();};
    const save=document.createElement('button');save.type='button';save.id='saveOnlyObsBtn';save.className='primary';save.textContent='Salvar somente OBS';document.getElementById('saveObsBtn').before(save);save.onclick=()=>{if(pending){status.textContent='Aguarde a foto terminar de carregar.';return;}capture();config.save();};
    return {refresh,capture,pending:()=>pending,clean};
  }
  return {mount,clean};
})();
